### ISSUE TITLE
Backend de atividades

### ISSUE THREAD

**Issue by TiagoGouvea** [Computadores-Para-Todos/computers-4-all-manager#15]
* Branch: 15-backend-de-atividades
* Depende de #17  e #18 

## Objetivo
Esta issue é criar a tabela de atividade, que registra tudo o que foi feito com um dispositivo, e serve como histórico completo de ações dos usuários.

* Seguir padrão implementado em user para schema, model, controler e rotas
* Se tiver alguma melhoria a sugerir, comente nesta issue para discutirmos

## Criar modelo e rotas
- [x] Declarar o schema de `activities`
- [x] Atributos: user_id, device_id, status_id, activity (indica o que foi feito "status", "user")
- [x] Definir created_at automático do sequelize, (não precisa de updated at) 

## Rotas
- [x] GET `/api/activities/` - Implementar na rota obtenção de todos os registros do banco, retornando em json
- [x] GET `/api/activities/{id}/` - Implementar rota para obter um único registro, caso não exista o registro retornar status `404 - not found`
- [x] POST `/api/activities/{id}/` - Implementar rota de POST para inclusão de registro, retornando o registro inserido
- [x] PUT `/api/activities/{id}/` - Implementar rota de PUT para alteração do registro
- [x] DEL `/api/activities/{id}/` - Implementar rota de DEL para excluir o registro
- [x] Quando houver um erro, retornar sempre `{error: $message}` para o cliente

## Permissões
Apenas admins podem listar, criar, alterar e excluir (por enquanto) - como depende da issue #3, deixe sem fazer até ela ser concluída

**Comment by maxjf1** [comment]
>  Atributos: ...,  activity (indica o que foi feito "status", "user")

@TiagoGouvea  Ficou meio ambiguo, o nome da tabela e do campo ser o mesmo, não consegui entender o objetivo de ambos

**Comment by TiagoGouvea** [comment]
@maxjf1 o "activity" seria tipo, exemplo:

- O computador foi colocado em renovação
{ 
user_id: (usuario que informou a atividade),
device_id: (dispositivo que está sendo referenciado),
status_id: (id do status "em renovação")
activity: (algo como "status_changed")
}

- O computador está sendo renovado pelo Tiago
{ 
...
status_id: (id do status "em renovação")
activity: (algo como "user_added")
}

- O computador está pronto para presentear
{ 
...
status_id: (id do status "presentear")
activity: (algo como "status_changed")
}

Tinha pensando algo mais ou menos assim.. esta tabela servir de log completo do que um dispositivo passou. Veja um exemplo de como fica no trello hoje:

![Cursor_e__24_-_Desktop_em_Computadores___Trello](https://user-images.githubusercontent.com/2242549/72204504-6df82700-3457-11ea-9a23-bf443785a725.png)

Os comentários, seriam outra tabela, que juntamente com a atividade daria o "fluxo" completo de um dispositivo. 

Sacou?
