### ISSUE TITLE
Backend de status

### ISSUE THREAD

**Issue by TiagoGouvea** [Computadores-Para-Todos/computers-4-all-manager#17]
* Branch: 17-backend-de-status

## Objetivo
Esta issue é criar a tabela de status, que indicarão os status de computadores e doações.

* Seguir padrão implementado em user para schema, model, controler e rotas
* Se tiver alguma melhoria a sugerir, comente nesta issue para discutirmos

## Criar modelo e rotas
- [x] Declarar o schema de `statuses`
- [x] Atributos: title (s), use (enum com "device" e "donation" por enquanto)
- [x] Definir created_at, updated_at automático do sequelize

## Rotas
- [x] GET `/api/statuses/` - Implementar na rota obtenção de todos os registros do banco, retornando em json
- [x] GET `/api/statuses/{id}/` - Implementar rota para obter um único registro, caso não exista o registro retornar status `404 - not found`
- [x] POST `/api/statuses/{id}/` - Implementar rota de POST para inclusão de registro, retornando o registro inserido
- [x] PUT `/api/statuses/{id}/` - Implementar rota de PUT para alteração do registro
- [x] DEL `/api/statuses/{id}/` - Implementar rota de DEL para excluir o registro
- [x] Quando houver um erro, retornar sempre `{error: $message}` para o cliente

## Permissões
- [x] Apenas admins podem listar, criar, alterar e excluir (por enquanto) - como depende da issue #3, deixe sem fazer até ela ser concluída

**Comment by maxjf1** [comment]
O nome statuses ficou bem estranho, pode causar confusão @TiagoGouvea

**Comment by TiagoGouvea** [comment]
Beleza. Eu estava escrevendo no plural porque imaginei que o sequelize iria "pluralizar" as tabelas. Sem problema.
