### ISSUE TITLE
Backend de doador

### ISSUE THREAD

**Issue by TiagoGouvea** [Computadores-Para-Todos/computers-4-all-manager#18]
* Branch: 18-backend-de-doador

## Objetivo
Esta issue é criar a tabela de doadores, que são as pessoas que doam os computadores para o projeto.

* Seguir padrão implementado em user para schema, model, controler e rotas
* Se tiver alguma melhoria a sugerir, comente nesta issue para discutirmos

## Criar modelo e rotas
- [x] Declarar o schema de `donators`
- [x] Atributos: name (s), email (unique), phone, notify (bool), notify_by (será "email", "whatsapp" ou "phone"), type (será "person", "company", "institution"), address_line_1, address_line_2, address_city, address_state, address_country
- [x] Definir created_at, updated_at automático do sequelize

## Rotas
- [x] GET `/api/donators/` - Implementar na rota obtenção de todos os registros do banco, retornando em json
- [x] GET `/api/donators/{id}/` - Implementar rota para obter um único registro, caso não exista o registro retornar status `404 - not found`
- [x] POST `/api/donators/{id}/` - Implementar rota de POST para inclusão de registro, retornando o registro inserido
- [x] PUT `/api/donators/{id}/` - Implementar rota de PUT para alteração do registro
- [x] DEL `/api/donators/{id}/` - Implementar rota de DEL para excluir o registro

## Permissões
- [x] Apenas admins podem listar, criar, alterar e excluir (por enquanto) - como depende da issue #3, deixe sem fazer até ela ser concluída

**Comment by maxjf1** [comment]
Já temos a tabela users. Talves seria melhor extendê-la ou usa-la @TiagoGouvea  , pelo menos nos dados que se repetem

**Comment by TiagoGouvea** [comment]
O doador não é um usuário, e esta é uma das tabelas que mais irá crescer. A desvantagem de extender é que teríamos com frequencia dados em user que não teríamos em doadores, com o tempo esta nova tabela teria muitos campos vazios. As lógicas das duas tabelas também são totalmente diferentes.

Acho que pode manter como `donator` mesmo, separado.

**Comment by maxjf1** [comment]
> - [ ] POST `/api/donators/{id}/` - Implementar rota de POST para inclusão de registro, retornando o registro inserido

Usada rota POST `/api/donators/`

**Comment by TiagoGouvea** [comment]
Ficou muito bom mesmo @maxjf1 ! Pode abrir o pull request!

👏👏👏
