### ISSUE TITLE
Backend de comentários

### ISSUE THREAD

**Issue by TiagoGouvea** [Computadores-Para-Todos/computers-4-all-manager#19]
* Branch: 14-backend-de-comentarios

## Objetivo
Esta issue é criar a tabela de comentários, por onde os usuários poderão enviar comentários acerca dos dispositivos.

* Seguir padrão implementado em user para schema, model, controler e rotas
* Se tiver alguma melhoria a sugerir, comente nesta issue para discutirmos

## Criar modelo e rotas
- [x] Declarar o schema de `comments`
- [x] Atributos: user_id, device_id, comment (s)
- [x] Definir created_at automático do sequelize

## Rotas
- [x] GET `/api/comments/` - Implementar na rota obtenção de todos os registros do banco, retornando em json
- [x] GET `/api/comments/{id}/` - Implementar rota para obter um único registro, caso não exista o registro retornar status `404 - not found`
- [x] POST `/api/comments/{id}/` - Implementar rota de POST para inclusão de registro, retornando o registro inserido
- [x] PUT `/api/comments/{id}/` - Implementar rota de PUT para alteração do registro
- [x] DEL `/api/comments/{id}/` - Implementar rota de DEL para excluir o registro
- [x] Quando houver um erro, retornar sempre `{error: $message}` para o cliente

## Permissões
Apenas admins podem listar, criar, alterar e excluir (por enquanto) - como depende da issue #3, deixe sem fazer até ela ser concluída

**Comment by maxjf1** [comment]
@TiagoGouvea Sugiro um nome como `message` ou `content` para o conteudo do comment, pois `Comment.comment` fica meio redundante (sera util caso o comment tenha novos campos no futuro)

**Comment by TiagoGouvea** [comment]
@maxjf1 concordo contigo, `content` é melhor mesmo. `message` pode ser que seja uma entidade no futuro, então `content` é melhor.

Pode ajustar e abrir merge quando estiver ok.
