### ISSUE TITLE
Layout da aplicação

### ISSUE THREAD

**Issue by TiagoGouvea** [Computadores-Para-Todos/computers-4-all-manager#21]
* Branch: 21-layout-da-aplicacao

* Como a issue de autenticação não foi concluída, porque está bloqueada pela do JWT, quando precisar testar o componente no projeto, chame ele diretamente do app, sem a autenticação.

## Objetivos
Criar interface geral do sistema, que será o que o usuário verá assim que autenticar. Pode usar o [Semantic-UI-Admin](https://github.com/ershagen/Semantic-UI-Admin) como base (para rodar ele use o pacote http-server).

## Storybook
- [x] Criar componente `<Layout>` que montará uma interface completa de admin

## Componente Layout
- [x] "Computadores para todos" no topo
- [x] Menu lateral com opções "Início", "Atividades", "Doadores", "Dispositivos", [separador], "Usuários"
- [x] Centro
- [x] React Router
- [x] Dropdown do usuário (canto superior direito) ter: "Perfil", [separador], "Sair"
- [x] Ao reduzir o tamanho da tela, o menu lateral deve ser ocultado e um botão "hamburger" deve ser exibido
- [x] Ao clicar no hamburger o menu aparece/desaparece

* O centro pode deixar em branco, pois terá outra issue para criação dele, para o dashboard efetivamente

**Comment by TiagoGouvea** [comment]
@allanmaral poderia por favor enviar um print aqui da interface como ficou?

**Comment by allanmaral** [comment]
**Layout desktop**
![desktop](https://user-images.githubusercontent.com/12241478/72205435-bf0d1880-3461-11ea-8081-aca9de97833e.png)

**Layout mobile/tela reduzida**
![Mobile](https://user-images.githubusercontent.com/12241478/72205683-dc8fb180-3464-11ea-8bd2-fe0f43e675f4.png)

**Comment by TiagoGouvea** [comment]
Excelente! Mandou bem!
