### ISSUE TITLE
Backend - suporte ES6

### ISSUE THREAD

**Issue by maxjf1** [Computadores-Para-Todos/computers-4-all-manager#28]
Configurar Babel com ES6 no backend, para ter sintaxes similares na API e no PWA

- [x] Ambiente de desenvolvimento (`dev`)
- [x] Build para produção funcionando (`build`)
- [x] atualizar instruções no README

**Comment by TiagoGouvea** [comment]
Mandou muito bem! Ficou ótimo!

Por favor abra um pull request para a gente fazer o merge.
