### ISSUE TITLE
Autenticação JWT - Frontend

### ISSUE THREAD

**Issue by TiagoGouvea** [Computadores-Para-Todos/computers-4-all-manager#4]
* Branch: 4-autenticao-jwt-frontend
* Depende de #6, #4 e #3 

# Objetivos
Implementar no frontend o registro e autenticação de usuários, utilizando formulário de signup, login e mantendo dado local para próximas requisições.

# Signup
- [x] View de signup - Implementar chamadas de signup utilizando como base interface criada em #5 
- [x] Não deixar registrar sem ter o email  (válido) em um campo e uma senha com pelo ao menos 6 caracteres

# Login
- [x] View de login - Implementar chamadas de login utilizando como base interface criada em #5 
- [x] Não deixar logar sem ter o email (válido) em um campo e uma senha com pelo ao menos 6 caracteres

# Dashboard
- [x] Após registrar ou logar, o usuário irá para a view de "Dashboard", que não terá nada atualmente
- [x] Exibir apenas um "Dashboard" escrito e um botão "logout"

# Logout
- [x] Ao clicar os dados de autenticação locais são apagados e o usuário é redirecionado para view inicial do projeto

**Comment by maxjf1** [comment]
# Especificações da API
Autenticação: Usa padrão [JSON Web token](https://jwt.io/introduction/). é preciso passar os cabeçalhos padrões na requisição (obter com login e salvar localmente pare reuso):

    Authorization: Bearer <token>

## Rotas: 

admin: (Retorna objeto do usuário)
- `/api/users (GET, POST)` - Obtém usuários / Cria usuários 
- `/api/users/:id (GET, PUT, DELETE)` - gerencia usuário, passando ID 

Usuário (retorna objeto simplificado do usuário e token
- `/api/users/signup (POST)` - Auto-cadastro
- `/api/users/login (GET)` - Autentica usuário
- `/api/users/whoami (GET)` - Obtém informações do usuário atual 


## Erros

geral: erros do sequelize (a melhorar)
401: autenticação/autorização necessária/inválida
500: Erro interno

**Comment by TiagoGouvea** [comment]
Excelente @allanmaral! Ficou muito bom! 

Já temos agora uma base para avançar no projeto!

👏👏👏

**Comment by TiagoGouvea** [comment]
@allanmaral conferindo melhor o código, vi que a chamada do layout, o que dá ao usuário o acesso ao sistema, está dentro do componente de autenticação... fiquei pensando em como essa chamada ao `<Layout/>` tivesse que estar lá fora no app.js, nas declarações da rota.
Se o usuário não está autenticado, ele vê a autenticação. Se autenticado vê o layout.
O que sugere?

**Comment by allanmaral** [comment]
@TiagoGouvea talvez seja interessante implementar um componente análogo ao `<Route />` do `react-router-dom` que só exiba a rota se o usuário estiver autenticado, caso contrário ele redireciona para a página de autenticação

**Comment by TiagoGouvea** [comment]
Uma maneira simples seria algo tal como [nesta resposta](https://stackoverflow.com/questions/59280476/how-to-protect-or-authenticate-react-route-using-react-router-dom-amplify). 
Teria que trazer a lógica de saber se está logado ou não para fora do container de autenticação e tal.

O que acha? Consegue ajustar?

**Comment by allanmaral** [comment]
Sim, era mais ou menos isso mesmo que eu estava pensando.
Fiz um pull request com as alterações #31 

Com as alterações, a lógica para verificação de usuário, criação dos dados no localstorage e logout ficaram espalhadas nos componentes, como não vamos utilizar redux/redux-saga, sugiro, em uma próxima issue, definir uma classe/hook para centralizar essa lógica

**Comment by TiagoGouvea** [comment]
Ficou muito bom! Agora sim!  👏👏👏

Já aprovei o merge, e vou fechar esta issue. 

Obrigado mais uma vez.
