### ISSUE TITLE
Componente DeviceCard

### ISSUE THREAD

**Issue by TiagoGouvea** [Computadores-Para-Todos/computers-4-all-manager#40]
* Branch: 40-componente-devicecard

## Objetivo
Fazer um componente que apresente um único computador (ou dispositivo) em uma lista.

## Exemplo
![Computadores___Trello](https://user-images.githubusercontent.com/2242549/72629614-6e992d80-392f-11ea-9451-6d233278e551.png)

## Ajustes de modelos
- [x] Adicionar ao modelo de device: `serial`, `collectedAt`
- [x] Adicionar ao modelo de donation: `collectedAt`
- [x] Adicionar ao modelo de status: `displayOrder`

## Device populado
```
{
   ... todos atributos do device,
   donation: {notify: "opção marcada lá", createdAt, collectedAt},
   donator: {name: "nome do doador"}
}
```

## Storybook `<DeviceCard/>`
- [x] Componente que recebe um "device populado" via props `data`
- [x] Os dados relevantes são exibidos, o id, title, devicetype (por ser um ícone talvez), nome do doador, "Iniciou doação a X dias" (antes de pegarmos) e "Conosco a X dias" (depois de pegarmos)
- [x] Callback de quando clica

**Comment by allanmaral** [comment]
Estimo que leve 2h para completar

**Comment by allanmaral** [comment]
## Visual do componente
![Screenshot_2020-01-17 Storybook](https://user-images.githubusercontent.com/12241478/72635036-a194ee80-393a-11ea-9c43-c84f216f181f.png)
