### ISSUE TITLE
Componente DeviceCardList

### ISSUE THREAD

**Issue by TiagoGouvea** [Computadores-Para-Todos/computers-4-all-manager#41]
* Branch: 41-componente-devicecardlist

## Objetivo
Receber uma lista de devices em uma única situação, e apresentar em diversos `DeviceCard`.

## Exemplo
![Computadores___Trello](https://user-images.githubusercontent.com/2242549/72629614-6e992d80-392f-11ea-9451-6d233278e551.png)

## Storybook `<DeviceCardList/>`
- [x] Componente que recebe um array de "device populados" via props `data`
- [x] Apresenta um card para cada registro

**Comment by allanmaral** [comment]
## View do componente `<DeviceCardList/>`
![Screenshot_2020-01-17 Storybook(1)](https://user-images.githubusercontent.com/12241478/72641372-c728f480-3948-11ea-97e1-a07e7f878658.png)

**Comment by TiagoGouvea** [comment]
Chique demais da conta! 

💯
