### ISSUE TITLE
Componente StatusDeviceList

### ISSUE THREAD

**Issue by TiagoGouvea** [Computadores-Para-Todos/computers-4-all-manager#42]
* Branch: 42-componente-statusdevicelist

## Objetivo
Obtem os dados de todos os devices por status e apresenta na interface usando os `DeviceList`.

## Exemplo
![Computadores___Trello](https://user-images.githubusercontent.com/2242549/72630737-c173e480-3931-11ea-9426-75da3d40f1d4.png)

## Storybook `<StatusDeviceList/>`
- [x] Componente que recebe um array de status com "devices populados" via props `data`
- [x] Para cada status exibir uma coluna usando `DeviceList`

## Container
- [x] Obter da API os  devices agrupos por status

## API
- [x] Criar endpoint `` que obtem os devices agrupados por status (por ordem de displayOrder), em uma única requisção
- [x] Fornecer os "devices populados" como esperado na issue #40 

```
{
   [ 
       { id: 1, title: "Avaliar", devices:  [coleção de devices nesta situação] },
       { id: 2, title: "Avaliando", devices:  [coleção de devices nesta situação] },
       ....
   ]
}
```

**Comment by allanmaral** [comment]
## View do componente `<StatusDeviceList/>`
![StatusDeviceList](https://user-images.githubusercontent.com/12241478/72645043-63ef9000-3951-11ea-9183-41d4ddb10a97.gif)

**Comment by TiagoGouvea** [comment]
Isso ai brother!

**Comment by TiagoGouvea** [comment]
Muito bom, valeu!
