### ISSUE TITLE
Iniciar Storybook - view autenticação

### ISSUE THREAD

**Issue by TiagoGouvea** [Computadores-Para-Todos/computers-4-all-manager#5]
* Branch: 5-iniciar-storybook-autenticao
* Comentar quanto tempo imagina que levará para implementar essa issue

## Objetivo
O objetivo desta issue é dá inicio ao StoryBook do projeto e criar o primeiro componente visual da aplicação. 

## Storybook
- [x] Adicionar storybook no projeto
- [x] Adicionar o componente que é a view de autenticação (descrito abaixo) no storybook
- [x] Adicionar no readme instruções de como rodar o storybook

## Componente visual de Autenticação
* Qual padrão de componentes você sugere? Comente na issue por favor
- [x] Exibir input de email e outro de senha, com botão "Criar conta"
- [x] Exibir também botão "Já tenho conta", que até pode manter os mesmos inputs (pra não perder o que o usuário preencheu) - com botão "Entrar agora"
- [x] Exigir os campos preenchidos (email válido, senha com pelo ao menos 6 caracteres) ao tentar entrar ou criar conta
- [x] O componente deve receber via prop a URL base da API, da qual irá chamar pra autenticar
- [x] Deverá receber duas props de callback, por onde o componete irá informar se tiver sucesso no login (status 200) (retornando o valor obtido da api), e outro para quando falhar no login (status != 200) (retornando valor também)
- [x] Não precisa implementar a chamada da API ainda, porque talvez ela ainda não tenha o endpoint, apenas simule um sucesso e falha nos botões existentes

## App.js
- [x] Importar a view de autenticação e deixar ela como padrão, como se estivesse funcionando mesmo, mas sem funcionar. Para quando alguem rodar o projeto ver a interface de login, ao invés da "hello world" do React.

**Comment by ruandsx** [comment]
Acredito que gastarei 2 dias pra realizar essa tarefa, ao iniciar por hoje.
Sobre o padrão, poderá ser utilizada lib de componentes visuais?? Se sim, sugiro o uso do semantic ui

**Comment by TiagoGouvea** [comment]
Testei aqui e ficou muito bom! Com esta issue pronta podemos liberar outras issues de view, que dependiam dela.

Obrigado @ruandsx!

Agora é só abrir um Pull Request para aprovação.
